
CATEGORIES = [
{'id': 0, 'name': 'fish', 'supercategory': 'None'},
{'id': 1, 'name': 'atlantic creolefish', 'supercategory': 'fish'},
{'id': 2, 'name': 'atlantic spadefish', 'supercategory': 'fish'},
{'id': 3, 'name': 'bar jack', 'supercategory': 'fish'},
{'id': 4, 'name': 'black margate', 'supercategory': 'fish'},
{'id': 5, 'name': 'blue tang surgeon', 'supercategory': 'fish'},
{'id': 6, 'name': 'brown chromis', 'supercategory': 'fish'},
{'id': 7, 'name': 'creolefish', 'supercategory': 'fish'},
{'id': 8, 'name': 'cuban hogfish', 'supercategory': 'fish'},
{'id': 9, 'name': 'doctorfish', 'supercategory': 'fish'},
{'id': 10, 'name': 'french angelfish', 'supercategory': 'fish'},
{'id': 11, 'name': 'french grunt', 'supercategory': 'fish'},
{'id': 12, 'name': 'gray angelfish', 'supercategory': 'fish'},
{'id': 13, 'name': 'indian triggerfish', 'supercategory': 'fish'},
{'id': 14, 'name': 'lookdown', 'supercategory': 'fish'},
{'id': 15, 'name': 'ocean surgeon', 'supercategory': 'fish'},
{'id': 16, 'name': 'porkfish', 'supercategory': 'fish'},
{'id': 17, 'name': 'purple queen anthias', 'supercategory': 'fish'},
{'id': 18, 'name': 'queen triggerfish', 'supercategory': 'fish'},
{'id': 19, 'name': 'sheepshead', 'supercategory': 'fish'},
{'id': 20, 'name': 'smallmouth grunt', 'supercategory': 'fish'},
{'id': 21, 'name': 'tomtate grunt', 'supercategory': 'fish'},
{'id': 22, 'name': 'white grunt', 'supercategory': 'fish'},
{'id': 23, 'name': 'white margate', 'supercategory': 'fish'},
{'id': 24, 'name': 'yellow bar jack', 'supercategory': 'fish'},
{'id': 25, 'name': 'reef butterflyfish', 'supercategory': 'fish'},
{'id': 26, 'name': 'albino???', 'supercategory':'fish'},
{'id': 27, 'name': 'undocumented', 'supercategory': 'fish'}
]
